name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H telegraminvi.vps.webdock.cloud >> ~/.ssh/known_hosts

      - name: Pull latest code on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no admin@telegraminvi.vps.webdock.cloud "cd /var/www/html && git pull" 